export const ActionType = {
  FETCH_CURRENT_POST_START: 'FETCH_CURRENT_POST_START',
  FETCH_CURRENT_POST_SUCCESS: 'FETCH_CURRENT_POST_SUCCESS',
  FETCH_CURRENT_POST_ERROR: 'FETCH_CURRENT_POST_ERROR',
  SET_CURRENT_POST: 'SET_CURRENT_POST',
  UPDATE_POST_START: 'UPDATE_POST_START',
  UPDATE_POST_SUCCESS: 'UPDATE_POST_SUCCESS',
  UPDATE_POST_ERROR: 'UPDATE_POST_ERROR',
  CREATE_COMMENT_START: 'CREATE_COMMENT_START',
  CREATE_COMMENT_SUCCESS: 'CREATE_COMMENT_SUCCESS',
  CREATE_COMMENT_ERROR: 'CREATE_COMMENT_ERROR',
};
export const llll = () => null;
